= How to document Pm4j =

== Tools ==
|=============================================
| Subject       | Tool
| Documentation | AsciiDoc 
| UML           | UMLet, Enterprise Architect
| Images        | E.g. GIMP
|=============================================
	
== Structure ==

=== General ===
1. A new folder/subproject pm4j-asciidoc in org.pm4j contains the ascciidoc documentation as well as all necessary resources (e.g. images, uml diagrams).
1. An index asciidoc file contains the table of contents (TOC).
1. The TOC consists of chapters as titles or links and documents as links. A chapter is represented by a link, if a chapter asciidoc exists.
1. Every document is represented by a document folder which consists of an asciidoc file and a resources folder.

==== Example ====
* org.pm4j
	** pm4j-asciidoc
		*** index.adoc (2)
		*** PM4J Basic concepts and design overview (3) [link, because a chapter document exists]
			**** resources (images etc.)
			**** PM4J Basic concepts and design overview.adoc
			**** Framework Goals and Guidelines (4)
				***** resources (images etc.)
				***** Framework Goals and Guidelines.adoc
				...
		*** PMObject (3) [title, because a chapter document does not exist] 
			**** enabled, visiable, readonly (4)
				***** resources
				***** enabled, visiable, readonly.adoc
				...

NOTE: The complete structure is defined in the https://wiki.hsdg-ad.int/GLOBE/index.php/TEBA_Component_Documentation[wiki]

=== Table of contents ===
The table of contents is written manually and consists of chapters as titles or links and documents as links. A chapter is represented by a link, if a chapter asciidoc exists. 	

NOTE: Is it possible to create the TOC via gradle?

== Using AsciiDoc ==
To publish the documentation you only have to push the asciidoc files and their resources into GitHub. 
GitHub itself is able to display the ascii in a well styled and formatted way. This means that no extra generation step is needed.

Note: Using the include functionality does not include the source document into the target document, but displays a link to the source document.

=== Naming conventions ===
- The names of folders and documents can be written in camel case and can also contain space characters. 
Because of some umlauts problems it would be a good idea not to use them. Also the documentation should be completely written in english, so that umlauts are not needed.
	
== Open questions ==
- Is it possible to generate the TOC via gradle task?
- What kind of uml tool do we use?
- Do we have any ordering problems?
